import json

from SRToolkit.dataset import SR_benchmark, SR_dataset
from SRToolkit.dataset.sampling import UniformSampling

# Sharing in SRToolkit splits along three axes that travel differently:
#   - Code   (custom approaches, constraints, samplers, ...): a `.srtk` bundle.
#   - Configs (plain JSON describing a component):            share the .json directly.
#   - Data   (.npz arrays in a versioned cache):              reached via the config's data_source,
#                                                             or shipped inside a self-contained archive.
# This example covers the two channels that need no extra files: the config recipe and the self-contained
# archive. Code bundles (.srtk) are deliberately omitted here: shareable classes must live in a named .py
# module, never in __main__ (a directly-run script), so they cannot be demonstrated in a single file. See the
# Sharing guide for pack()/install().

if __name__ == "__main__":
    # Build a small sampling-backed benchmark to share. Because each dataset carries a seeded SampleSource,
    # its data regenerates identically on any machine -- so the config alone is enough to reproduce the data.
    bm = SR_benchmark("shared_demo", version="1.0.0")
    bm.add_from_samplers(
        ground_truth=["X_0", "^2", "+", "1"],
        samplers=[UniformSampling(0.5, 5.0, uses_negative=False)],
        dataset_name="eq1",
        original_equation="x^2 + 1",
        n_samples=2000,
        seed=42,
        success_threshold=1e-6,
    )
    bm.add_from_samplers(
        ground_truth=["sin", "(", "X_0", ")", "+", "X_1"],
        samplers=[UniformSampling(0.5, 5.0), UniformSampling(0.5, 5.0)],
        dataset_name="eq2",
        original_equation="sin(x0) + x1",
        n_samples=2000,
        seed=42,
        success_threshold=1e-6,
    )

    # --------------------------------- Channel 1: the config recipe (JSON) ------------------------------------
    # to_dict() returns a pure, data-free dict: each dataset keeps only its samplers and a data_source pointer.
    # The recipient's from_dict regenerates the arrays by sampling (reproducibly, thanks to the fixed seeds).
    # This is the lightweight channel -- but the recipient must be able to reach/regenerate the data.
    config = bm.to_dict()
    with open("shared_demo.json", "w") as fh:
        json.dump(config, fh, indent=2)

    bm_recipe = SR_benchmark.from_dict("shared_demo.json")
    ds_recipe = bm_recipe.create_dataset("eq1")  # data regenerated by sampling here
    print("From config recipe:", ds_recipe.X.shape)

    # ------------------------------ Channel 2: a self-contained archive (.zip) --------------------------------
    # to_archive() writes a single .zip holding benchmark.json plus data/<dataset>.npz for every dataset. The
    # recipient needs no network access, no samplers, and no seed agreement -- the exact arrays travel inside.
    bm.to_archive("shared_demo.zip")
    bm_archive = SR_benchmark.from_archive("shared_demo.zip")
    ds_archive = bm_archive.create_dataset("eq2")  # data extracted from the zip into the cache
    print("From self-contained archive:", ds_archive.X.shape)

    # The same pair exists for a single SR_dataset.
    ds = SR_dataset.from_samplers(
        ground_truth=["X_0", "^2", "+", "1"],
        samplers=[UniformSampling(0.5, 5.0, uses_negative=False)],
        n_samples=2000,
        seed=42,
        dataset_name="single_eq",
        benchmark="shared_demo",  # namespace required before archiving/serialising
        version="1.0.0",
    )
    ds.to_archive("single_eq.zip")
    ds_loaded = SR_dataset.from_archive("single_eq.zip")
    print("Single-dataset archive round trip:", ds_loaded.X.shape)
