"""
This module contains the SR_approach class, which is the base class for all symbolic regression approaches.
"""
from SRToolkit.evaluation import SR_evaluator


class SR_approach:
    def __init__(self, name: str):
        """
        The base class for all symbolic regression approaches. Any symbolic regression approach should inherit from
        this class.

        Args:
            name: The name of the approach.
        """
        self.name = name

    def search(self, sr_evaluator: SR_evaluator):
        """
        Implements the logic of the symbolic regression approach. The approach should use the SR_evaluator instance
        to evaluate the expressions it generates.

        Args:
            sr_evaluator: The SR_evaluator instance to use for evaluating the expressions generated by the approach

        """
        raise NotImplementedError