name: ci
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install ruff
        run: pip install ruff
      - name: Check linting
        run: ruff check SRToolkit/
      - name: Check formatting
        run: ruff format --check SRToolkit/

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install ".[dev]"
      - name: Run tests
        run: pytest --doctest-modules --cov=SRToolkit --cov-report=term-missing SRToolkit/ tests/

  typecheck:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install ".[dev]"
      - name: Run mypy
        run: mypy SRToolkit/ --ignore-missing-imports
